/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.qlnt.ui;

import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author monst
 */
public class BanHangJPanel extends javax.swing.JPanel {

    /** Creates new form TongQuanJPannel */
    public BanHangJPanel() {
        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grGioiTinh = new javax.swing.ButtonGroup();
        pnlGioHang = new javax.swing.JPanel();
        btnSaoChepHD = new javax.swing.JButton();
        txtTimKiemThuoc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTimKiemThuoc = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        pnlHoaDon = new javax.swing.JPanel();
        txtTimKiemHD = new javax.swing.JTextField();
        btnThemKH = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTimKiemKH = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtNamSinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtKhachTT = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnHD = new javax.swing.JButton();
        btnTT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 570));
        setMinimumSize(new java.awt.Dimension(1000, 570));
        setPreferredSize(new java.awt.Dimension(1000, 570));

        pnlGioHang.setBackground(new java.awt.Color(255, 255, 255));
        pnlGioHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N
        pnlGioHang.setMaximumSize(new java.awt.Dimension(500, 600));
        pnlGioHang.setMinimumSize(new java.awt.Dimension(500, 600));
        pnlGioHang.setPreferredSize(new java.awt.Dimension(500, 600));

        btnSaoChepHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnSaoChep.png"))); // NOI18N
        btnSaoChepHD.setToolTipText("Sao chép hóa đơn đã bán");
        btnSaoChepHD.setBorder(null);
        btnSaoChepHD.setContentAreaFilled(false);
        btnSaoChepHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaoChepHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaoChepHDMouseExited(evt);
            }
        });

        txtTimKiemThuoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTimKiemThuoc.setToolTipText("");
        txtTimKiemThuoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(160, 160, 160)));
        txtTimKiemThuoc.setOpaque(false);
        txtTimKiemThuoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemThuocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemThuocFocusLost(evt);
            }
        });

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGioHang);

        tblTimKiemThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTimKiemThuoc);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnSearch.png"))); // NOI18N

        javax.swing.GroupLayout pnlGioHangLayout = new javax.swing.GroupLayout(pnlGioHang);
        pnlGioHang.setLayout(pnlGioHangLayout);
        pnlGioHangLayout.setHorizontalGroup(
            pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGioHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGioHangLayout.createSequentialGroup()
                        .addGroup(pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaoChepHD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlGioHangLayout.createSequentialGroup()
                        .addGroup(pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlGioHangLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(12, 12, 12)
                                .addComponent(txtTimKiemThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlGioHangLayout.setVerticalGroup(
            pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGioHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaoChepHD)
                .addGap(23, 23, 23)
                .addGroup(pnlGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnlHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N
        pnlHoaDon.setMaximumSize(new java.awt.Dimension(500, 600));
        pnlHoaDon.setMinimumSize(new java.awt.Dimension(500, 600));
        pnlHoaDon.setPreferredSize(new java.awt.Dimension(500, 600));

        txtTimKiemHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTimKiemHD.setToolTipText("");
        txtTimKiemHD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(160, 160, 160)));
        txtTimKiemHD.setOpaque(false);
        txtTimKiemHD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemHDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemHDFocusLost(evt);
            }
        });

        btnThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnThemKHMoi.png"))); // NOI18N
        btnThemKH.setToolTipText("Thêm khách hàng mới");
        btnThemKH.setBorder(null);
        btnThemKH.setContentAreaFilled(false);
        btnThemKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemKHMouseExited(evt);
            }
        });

        tblTimKiemKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblTimKiemKH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nhân viên:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtNV.setEditable(false);
        txtNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNV.setOpaque(false);
        jPanel4.add(txtNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 161, 26));

        jLabel2.setText("Ngày tạo:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        txtNgayTao.setEditable(false);
        txtNgayTao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNgayTao.setOpaque(false);
        jPanel4.add(txtNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 140, 26));

        txtTenKH.setEditable(false);
        txtTenKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTenKH.setOpaque(false);
        jPanel4.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 350, 26));

        jLabel3.setText("Tên khách hàng:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setText("Giới tính:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        grGioiTinh.add(rdoNam);
        rdoNam.setText("Nam");
        jPanel4.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        grGioiTinh.add(rdoNu);
        rdoNu.setText("Nữ");
        jPanel4.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel5.setText("Năm sinh:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        txtNamSinh.setEditable(false);
        txtNamSinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNamSinh.setOpaque(false);
        jPanel4.add(txtNamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 140, 26));

        jLabel6.setText("SDT:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtDiem.setEditable(false);
        txtDiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtDiem.setOpaque(false);
        jPanel4.add(txtDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 110, 26));

        jLabel7.setText("Điểm thân thiên:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        txtTongTien.setEditable(false);
        txtTongTien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTongTien.setOpaque(false);
        jPanel4.add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 380, 26));

        jLabel8.setText("Tổng tiền:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtSDT.setEditable(false);
        txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSDT.setOpaque(false);
        jPanel4.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 180, 26));

        jLabel17.setText("Ghi chú:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtKhachTT.setEditable(false);
        txtKhachTT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtKhachTT.setOpaque(false);
        jPanel4.add(txtKhachTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 110, 26));

        jLabel18.setText("Tiền thừa:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        txtTienThua.setEditable(false);
        txtTienThua.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTienThua.setOpaque(false);
        jPanel4.add(txtTienThua, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 150, 26));

        jLabel19.setText("Khách thanh toán:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtGhiChu.setRows(5);
        txtGhiChu.setWrapStyleWord(true);
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtGhiChu.setOpaque(false);
        jScrollPane6.setViewportView(txtGhiChu);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 390, 60));

        btnHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnInHD.png"))); // NOI18N
        btnHD.setBorder(null);
        btnHD.setContentAreaFilled(false);
        btnHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHDMouseExited(evt);
            }
        });
        btnHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDActionPerformed(evt);
            }
        });
        jPanel4.add(btnHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 190, 30));

        btnTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnThanToan.png"))); // NOI18N
        btnTT.setBorder(null);
        btnTT.setContentAreaFilled(false);
        btnTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTTMouseExited(evt);
            }
        });
        jPanel4.add(btnTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 190, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlnt/icon/btnSearch.png"))); // NOI18N

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlHoaDonLayout.createSequentialGroup()
                        .addGroup(pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTimKiemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addGroup(pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThemKH))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemThuocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemThuocFocusGained
        if(txtTimKiemThuoc.getText().equals("Nhập tên thuốc cần tìm")){
            txtTimKiemThuoc.setText("");
            
        }
    }//GEN-LAST:event_txtTimKiemThuocFocusGained

    private void txtTimKiemThuocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemThuocFocusLost
        if(txtTimKiemThuoc.getText().equals("")){
            txtTimKiemThuoc.setText("Nhập tên thuốc cần tìm");
        }
    }//GEN-LAST:event_txtTimKiemThuocFocusLost

    private void txtTimKiemHDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemHDFocusGained
        if(txtTimKiemHD.getText().equals("Nhập tên khách hàng cần tìm")){
            txtTimKiemHD.setText("");
        }
    }//GEN-LAST:event_txtTimKiemHDFocusGained

    private void txtTimKiemHDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemHDFocusLost
        if(txtTimKiemHD.getText().equals("")){
            txtTimKiemHD.setText("Nhập tên khách hàng cần tìm");
        }
    }//GEN-LAST:event_txtTimKiemHDFocusLost

    private void btnHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHDActionPerformed

    private void btnSaoChepHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaoChepHDMouseEntered
        changeIcon(1, btnSaoChepHD,  "src//com//qlnt//icon//btnSaoChep_hover.png");       
    }//GEN-LAST:event_btnSaoChepHDMouseEntered

    private void btnSaoChepHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaoChepHDMouseExited
        changeIcon(2, btnSaoChepHD, "src//com//qlnt//icon//btnSaoChep.png");
    }//GEN-LAST:event_btnSaoChepHDMouseExited

    private void btnThemKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemKHMouseEntered
        changeIcon(1, btnThemKH, "src//com//qlnt//icon//btnThemKHMoi_hover.png");
    }//GEN-LAST:event_btnThemKHMouseEntered

    private void btnThemKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemKHMouseExited
        changeIcon(2, btnThemKH, "src//com//qlnt//icon//btnThemKHMoi.png");
    }//GEN-LAST:event_btnThemKHMouseExited

    private void btnTTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTMouseEntered
        changeIcon(1, btnTT, "src//com//qlnt//icon//btnThanToan_hover.png");
    }//GEN-LAST:event_btnTTMouseEntered

    private void btnTTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTMouseExited
        changeIcon(2, btnTT, "src//com//qlnt//icon//btnThanToan.png");
    }//GEN-LAST:event_btnTTMouseExited

    private void btnHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseEntered
        changeIcon(1, btnHD, "src//com//qlnt//icon//btnInHD_hover.png");
    }//GEN-LAST:event_btnHDMouseEntered

    private void btnHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseExited
        changeIcon(2, btnHD, "src//com//qlnt//icon//btnInHD.png");
    }//GEN-LAST:event_btnHDMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHD;
    private javax.swing.JButton btnSaoChepHD;
    private javax.swing.JButton btnTT;
    private javax.swing.JButton btnThemKH;
    private javax.swing.ButtonGroup grGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlGioHang;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblTimKiemKH;
    private javax.swing.JTable tblTimKiemThuoc;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtKhachTT;
    private javax.swing.JTextField txtNV;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTimKiemHD;
    private javax.swing.JTextField txtTimKiemThuoc;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
   void init() {
       initComponents();
       txtTimKiemThuoc.setText("Nhập tên thuốc cần tìm");
       txtTimKiemHD.setText("Nhập tên khách hàng cần tìm");
   }
   void changeIcon(int so, JButton btn, String url) {
        if (so == 1) {
            Image img = getToolkit().createImage(url);
            btn.setIcon(new ImageIcon(img));
            btn.setCursor(new Cursor(HAND_CURSOR));
        } else {
            Image img = getToolkit().createImage(url);
            btn.setIcon(new ImageIcon(img));
        }
    }
}
